### ISSUE TITLE
Match Prop Rotation Before Tool Activation

### ISSUE THREAD

**Issue by Cgameworld** [algernon-A/LineToolLite#1]
First off, awesome mod! 

When placing prop fences with devui (fence networks don't seem to work), the rotation of the fence prop does not match the rotation of the prop before activating the tool.

![linetool-example](https://github.com/algernon-A/LineToolLite/assets/49973689/d6b04a4e-dcec-45f8-95ae-67090242cfa8)

This makes it hard to precisely place directional props as the manual rotation arrow buttons might not be precise enough over long distances to match edges

**Comment by algernon-A** [comment]
Confirmed!  Yeah, there's no fence mode currently, and I need to add one.

I'm assuming that what you really want is for it to be aligned with the line, and not just your original alignment?

**Comment by Cgameworld** [comment]
Ideally yes

**Comment by algernon-A** [comment]
A fence mode has been added in version 1.0.3 - is this what you were after?

**Comment by Cgameworld** [comment]
Awesome, yes that's what I was looking for
