### ISSUE TITLE
Request BepInEx 6 support

### ISSUE THREAD

**Issue by CplusplusB** [algernon-A/LineToolLite#12]
Would be nice to have an release of this mod with BepInEx 6 support. Many mods deploy both support BepInEx5 and 6, would be nice to have it here. I cannot use this useful LineTool with BepInEx 5 because 5 and 6 are not compatible

**Comment by algernon-A** [comment]
I won't say no, but I want to make it clear that it's a very low priority.

Most of the current Cities Skylines II modding scene is using BepInEx 5, so support for 6 is already niche anyway.  Add that to the fact that BepInEx will soon be obsolete for Cities Skylines II modding anyway so any effort I expend on BepInEx is wasted time and effort that would be better spent on more productive and longer-lasting features, and I'm sure you can see why this is very low on the priority list.  If I get particularly inspired, sure, but if I'm honest official modding support (and the removal of BepInEx entirely) is likely to happen first.

**Comment by algernon-A** [comment]
Closing as official modding support has arrived and Line Tool Lite has been replaced by Line Tool (without BepInEx).
