### ISSUE TITLE
[Suggestion] Adding a rotation option for line mode

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [algernon-A/LineToolLite#14]
Objects like NoParkingStripingDecal02 will be lined in the wrong direction in the current version, it's hard to know which direction players want to line objects, so please add an option for it.
![image](https://github.com/algernon-A/LineToolLite/assets/31107435/39a73066-af42-4e67-8d36-c4d6a5e37b48)

**Comment by algernon-A** [comment]
Implemented in the full Line Tool.
