### ISSUE TITLE
Old trees reset when continous line is used

### ISSUE THREAD

**Issue by meda22** [algernon-A/LineToolLite#3]
I've found out bit strange issue. When I finish line with SHIFT+left_click and then stop further using of tool by right_click a selected tree stays in a cursor. When I move that cursor over any already existing tree, it resets to a small sampling. 

Please see attached screenshots.
![line1](https://github.com/algernon-A/LineToolLite/assets/6073782/3adb39ea-6194-48fc-888c-ba52753e150c)
![line2](https://github.com/algernon-A/LineToolLite/assets/6073782/c988ee07-5f2c-4229-8d29-3c9add8e829f)
![line3](https://github.com/algernon-A/LineToolLite/assets/6073782/c8cc60e8-37f2-4f3b-833c-dbab7ce9cf79)

And thanks for a great mod - detailing is much more easier now :)

**Comment by algernon-A** [comment]
The cursor is normal (to show you what object is selected).  The game does have interesting behavior around tree ages, and yes, it looks as though the cursor is resetting the tree ages.  I'll see what I can do.

**Comment by algernon-A** [comment]
I've made some tweaks in version 1.0.4, just published - does this fix it for you?

**Comment by meda22** [comment]
I've tried the new version and it works like a charm 👍 no more resetting of trees :)
