### ISSUE TITLE
Would be nice if it could keep the tree selection UI open when on tree mode

### ISSUE THREAD

**Issue by fleps** [algernon-A/LineToolLite#7]
Right now every time we activate it takes away the tree selection UI.

So if I'm doing lots of line tree placements, every time I want to change the tree I need to hit the tree button to open the UI, the mod UI goes away, then select a new tree, then hit CTRL+L.

The fact that we can't customize the shortcut  also doesn't help, as CTRL + L isn't one we can hit with left-hand easily

Great work btw!

**Comment by algernon-A** [comment]
Thanks!

Yes, you've just hit on the two biggest pain points that I'm addressing after the addition of tooltips and localization in 1.2 (just uploaded).

Development is now focusing on integrating the tool with the default object tool (as with the CS1 version) so you'll be able to change prefabs while still using the tool (and switch to/from the tool without a hotkey - just like you can change modes in the network tool).

I'm also working on customizable input bindings integrating with the game's inbuilt input system - that's actually been a very complex piece of work (I estimate I've spent at least 20 hours on that alone so far).  I'm very near to a releasable version, but still have two hurdles left (one of which is quite significant).

**Comment by fleps** [comment]
> Thanks!
> 
> Yes, you've just hit on the two biggest pain points that I'm addressing after the addition of tooltips and localization in 1.2 (just uploaded).
> 
> Development is now focusing on integrating the tool with the default object tool (as with the CS1 version) so you'll be able to change prefabs while still using the tool (and switch to/from the tool without a hotkey - just like you can change modes in the network tool).
> 
> I'm also working on customizable input bindings integrating with the game's inbuilt input system - that's actually been a very complex piece of work (I estimate I've spent at least 20 hours on that alone so far). I'm very near to a releasable version, but still have two hurdles left (one of which is quite significant).

That is really nice, and big kudos.
I can image that modding at this stage before the official mod support is launched is being a pain.
Regarding the in-game input system, I have seen other mods that uses it to setup bindings, not sure if would help you tell you which one (I don't remember by head but could check)

Thanks for replying and keep up the great work!

**Comment by algernon-A** [comment]
If you do know of someone who's already figured out the game's input system bindings then I'm definitely interested in taking a look, thanks!  I'd rather not have to resort to menu selections instead of using dynamic key bindings and conflict detection.

**Comment by fleps** [comment]
> If you do know of someone who's already figured out the game's input system bindings then I'm definitely interested in taking a look, thanks! I'd rather not have to resort to menu selections instead of using dynamic key bindings and conflict detection.

Hey man, I took a look and I got it wrong, the mods are not using the game Input, they just using the game Options screen to create their own options here, not sure if it helps in any way (529 Tiles and Tree Controller are the mods)

Sorry!

**Comment by algernon-A** [comment]
No worries!  And yeah, I know those two mods - I wrote one and helped a bit with the other :)

I'm making very good progress and have just cracked the most significant outstanding problem, so I'm not going to resort to setting file editing just yet....

**Comment by algernon-A** [comment]
I think both issues have been addressed with the new 1.3 update (tree selection panel remains open, and the hotkey has been removed entirely as the mod is now activated via the UI).

Feel free to reopen this if you disagree.

**Comment by fleps** [comment]
The new version looks / works awesome man, great work <3
