### ISSUE TITLE
Please include patch notes on Thunderstore.

### ISSUE THREAD

**Issue by AgentX2006** [algernon-A/LineToolLite#8]
Just a request to add what changed when releasing an update on the Thunderstore page. When there is an update I have to go to the Thunderstore page to get the github link and finally go to the releases section on github just to see what was changed.

**Comment by algernon-A** [comment]
Fair enough - will try to do so at the next update.

**Comment by algernon-A** [comment]
After a couple of unsuccessful attempts, finally got Thunderstore to recognize the changelog with the 1.3 release.
