### ISSUE TITLE
Game Error

### ISSUE THREAD

**Issue by fleps** [algernon-A/LineToolLite#9]
Hi!

I was playing last night and game crashed out of nowhere while I was doing some detailing (creating custom parks, using the Line Tool a lot).
Once restarted, oddly my 3 auto-saves stopped working, they would no longer load, game crashed instantly, gladly my normal save works, lost an hour or so of decorating but no biggie.

Went back to the game today and started redoing my decorating and while doing so I noted that Line Tool started acting weird, when I have a tree or bush selected and activate line tool the tree goes transparent each time I move the mouse, I can no longer see them as I'm placing the line, just the blue silhouette.

I then pressed ESC to go back to normal mode (I also had the dev object panel open as I was using the surface tool prior to start adding the trees) and the game error window popped, with 2 errors:

```
[ERROR]  JS Error (Stack): TypeError: Cannot read properties of null (reading 'classList')
    at <anonymous>:1:48
Colossal.Logging.CustomLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:LogFormat(LogType, String, Object[])
Colossal.Logging.UnityLogger:Log(Level, String, Exception)
Colossal.Logging.UnityLogger:Error(Object)
Colossal.UI.LogHandler:WriteLog(Severity, String, UInt32)
cohtml.Net.ILogHandler:SwigDirectorWriteLog(Int32, String, UInt32)
cohtml.Net.cohtmlNativePINVOKE:View_ExecuteScript(HandleRef, String)
cohtml.Net.View:ExecuteScript(String)
LineTool.LineToolUISystem:ExecuteScript(View, String)
LineTool.LineToolUISystem:OnUpdate()
Unity.Entities.SystemBase:Update()
Game.UpdateSystem:Update(SystemUpdatePhase)
Game.UI.UIUpdateSystem:OnUpdate()
Unity.Entities.SystemBase:Update()
Game.UpdateSystem:Update(SystemUpdatePhase)
Game.SceneFlow.GameManager:UpdateWorld()
Game.SceneFlow.GameManager:Update()

---
[ERROR]  JS Error (Line): document.getElementById("line-tool-mode-point").classList.add("selected");
Colossal.Logging.CustomLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:LogFormat(LogType, String, Object[])
Colossal.Logging.UnityLogger:Log(Level, String, Exception)
Colossal.Logging.UnityLogger:Error(Object)
Colossal.UI.LogHandler:WriteLog(Severity, String, UInt32)
cohtml.Net.ILogHandler:SwigDirectorWriteLog(Int32, String, UInt32)
cohtml.Net.cohtmlNativePINVOKE:View_ExecuteScript(HandleRef, String)
cohtml.Net.View:ExecuteScript(String)
LineTool.LineToolUISystem:ExecuteScript(View, String)
LineTool.LineToolUISystem:OnUpdate()
Unity.Entities.SystemBase:Update()
Game.UpdateSystem:Update(SystemUpdatePhase)
Game.UI.UIUpdateSystem:OnUpdate()
Unity.Entities.SystemBase:Update()
Game.UpdateSystem:Update(SystemUpdatePhase)
Game.SceneFlow.GameManager:UpdateWorld()
Game.SceneFlow.GameManager:Update()
```

Not saying the mod caused the crash, just reporting the whole picture.
I was using the v 1.3, updating to the 1.3.2 now to check if anything changes.

**Comment by fleps** [comment]
Nop, same behavior with 1.3.2

I'm being crazy and this was always like this? I can only see the tree when line tool is selected if not moving the mouse, but once started placing even with the mouse not moving the tree is full transparent with only the blue silhouette is visible.

**Comment by algernon-A** [comment]
Thanks about the LOD cross-fade; I'll look into it.

I believe the JS error was a race condition which relates to code that was removed in 1.3.2 - please let me know if you see it again.

**Comment by algernon-A** [comment]
Closing as UI has been overhauled with introduction of official UI modding support in Line Tool.
